### ISSUE TITLE
data_process/ngram_sample/trainfile-5.count这个文件去哪获得？

### ISSUE THREAD

**Issue by alao556** [BAORONGZHOU/span-fine-tuning#1]
data_process/ngram_sample/make_ngram_dict_script.py中，打开的第一个文件就是data_process/ngram_sample/trainfile-5.count，这个文件如何获得？

**Comment by BAORONGZHOU** [comment]
这个文件是通过srlim，基于wiki103这个corpus统计出来的ngram statistics，可能由于太大了没有上传，你可以参考https://blog.csdn.net/lv_xinmy/article/details/8572496，得到count文件，或者把你的邮箱给我，目前我在旅游等我回去了传给你

**Comment by alao556** [comment]
谢谢在百忙之中回复我，这是我的邮箱：alao556@live.com
祝您旅游愉快~

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by nuochenpku** [comment]
你好，你有收到trainfile-5.count这个文件吗
